[local]
localhost

[mongodb]
mongodb.chinnu.store

[redis]
redis.chinnu.store

[mysql]
mysql.chinnu.store

[rabbitmq]
rabbitmq.chinnu.store

[catalogue]
catalogue.chinnu.store

[user]
user.chinnu.store

[cart]
cart.chinnu.store

[shipping]
shipping.chinnu.store

[payment]
payment.chinnu.store

[frontend]
chinnu.store